language: node_js

node_js:
  - 0.10
  - 0.12

sudo: false

env:
  global:
    - NODE_ENV=test
    - SOME_AUTHOR='Ernest Hemingway'

before_script:
  - export PATH=$PATH:$PWD/node_modules/.bin
  - export TRAVIS_CI_3894_NODE_PATH=$(nvm which $TRAVIS_NODE_VERSION)

script: npm run cover

after_success: ./tasks/travis_after_success.sh

